[package]
name = "tiny-adnl"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[dependencies]
aes = { version = "0.7", features = ["ctr"] }
async-trait = "0.1"
anyhow = "1.0"
base64 = "0.13"
curve25519-dalek = "3.1"
crossbeam-queue = "0.3"
dashmap = "4.0"
ed25519-dalek = "1.0"
generic-array = "0.14"
hex = "0.4"
log = "0.4"
parking_lot = "0.11"
rand = "0.7"
raptorq = { git = "https://github.com/Rexagon/raptorq.git" }
serde = "1.0"
sha2 = "0.9"
thiserror = "1.0"
tokio = { version = "1.6", features = ["sync", "net", "rt", "time", "io-util"] }
x25519-dalek = "1"

ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[dependencies.ton_api]
git = "https://github.com/broxus/ton-labs-tl.git"
branch = "original"
package = "ton_api"
default-features = false
features = ["ton_api"]
